FROM alpine/git
RUN mkdir /var/jenkins-backup

ENV BACKUP_BRANCH_NAME="%BACKUP_BRANCH_NAME%"
ENV JENKINS_BACKUP_REPOSITORY = "%JENKINS_BACKUP_REPOSITORY%"
RUN git clone --single-branch --branch %BACKUP_BRANCH_NAME% %JENKINS_BACKUP_REPOSITORY% /var/jenkins-backup && ls /var/jenkins-backup
RUN cd /var/jenkins-backup/%BACKUP_BRANCH_NAME%/jenkins_home && cp  . ../../
RUN cd /var/jenkins-backup && rm -rf %BACKUP_BRANCH_NAME%
CMD [ "sh" ]



