FROM alpine/git
RUN mkdir /var/jenkins-backup

ENV BACKUP_BRANCH_NAME="%BACKUP_BRANCH_NAME%"
ENV JENKINS_BACKUP_REPOSITORY = "%JENKINS_BACKUP_REPOSITORY%"
RUN git clone --single-branch --branch %BACKUP_BRANCH_NAME% %JENKINS_BACKUP_REPOSITORY%
COPY  ./jenkins-backup/%BACKUP_BRANCH_NAME%/jenkins_home/ /var/jenkins-backup/

CMD [ "sh" ]



